<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class UsuarioSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('usuarios')->insert([
            // --- ADMIN ---
            [
                'nombre' => 'Propietario Marcos',
                'email' => 'admin@gym.com',
                'contrasena' => bcrypt('admin123'),
                'fecha_registro' => now(),
                'is_propietario' => true,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => false,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // --- SECRETARIA ---
            [
                'nombre' => 'Mariela Macias',
                'email' => 'secretaria@gym.com',
                'contrasena' => bcrypt('secretaria123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => true,
                'is_instructor' => false,
                'is_clientes' => false,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // --- INSTRUCTOR ---
            [
                'nombre' => 'Rolando Camino',
                'email' => 'instructor@gym.com',
                'contrasena' => bcrypt('instructor123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => true,
                'is_clientes' => false,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // --- CLIENTES ---
            [
                'nombre' => 'Mario Jimenez',
                'email' => 'cliente@gym.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Ana García',
                'email' => 'ana.garcia@gmail.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Carlos Mendoza',
                'email' => 'carlos.mendoza@hotmail.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Laura Fernández',
                'email' => 'laura.fernandez@gmail.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Roberto Silva',
                'email' => 'roberto.silva@yahoo.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Patricia Rojas',
                'email' => 'patricia.rojas@gmail.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Diego Torres',
                'email' => 'diego.torres@outlook.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Sofía Vargas',
                'email' => 'sofia.vargas@gmail.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Andrés Morales',
                'email' => 'andres.morales@hotmail.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Valentina Cruz',
                'email' => 'valentina.cruz@gmail.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Fernando Paz',
                'email' => 'fernando.paz@yahoo.com',
                'contrasena' => bcrypt('cliente123'),
                'fecha_registro' => now(),
                'is_propietario' => false,
                'is_secretaria' => false,
                'is_instructor' => false,
                'is_clientes' => true,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
